steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/randomrails-$BRANCH_NAME:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/randomrails-$BRANCH_NAME:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'randomrails-$BRANCH_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/randomrails-$BRANCH_NAME:$SHORT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/randomrails-$BRANCH_NAME:$SHORT_SHA'