version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.development
      context: .
    volumes:
      - ./backend/crayonrails:/app
    environment:
      PRODUCTION_STATICFILES: "true"
    command: python manage.py runserver 0:8000
    ports:
      - 8000:8000