# Generated by Django 3.0.5 on 2020-04-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_lobbyaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerslot',
            name='color',
        ),
        migrations.RemoveField(
            model_name='playerslot',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='playerslot',
            name='index',
        ),
        migrations.RemoveField(
            model_name='playerslot',
            name='screenname',
        ),
    ]
