# Generated by Django 3.0.5 on 2020-04-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200415_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaction',
            name='data',
            field=models.TextField(),
        ),
    ]
