# Generated by Django 3.0.5 on 2020-10-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200418_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslot',
            name='screen_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
