# Generated by Django 3.0.5 on 2020-10-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playerslot_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.PlayerSlot'),
        ),
    ]
